### PR TITLE
change html title - (initial pull request)

### PR DESCRIPTION
**Pull request by NikolaGolubovic**

### CODE REVIEW

**Comment by ghost** [comment]
image
Remove "outline" from the input field. Check mobile resolution - "overflow-x".

**Comment by NikolaGolubovic** [comment]
> Check mobile resolution - "overflow-x".

@sandraristic7 i am not sure where do you see a problem?

**Comment by ghost** [comment]
@NikolaGolubovic 
image
iPhone 6,7,8

**Comment by ghost** [comment]
Great!

**Pull request merged**
